#
# Build configuration for Circle CI
#
version: 2
jobs:
  build:
    docker:    # alternativ "machine/docker" (machine is not working on CirleCi Free Account)
      # - image: circleci/openjdk:8-jdk-browsers    #"cirlceci/" im Pfad notwendig, damit der Circlci Container "" gefunden wird
      - image: circleci/android:api-25-alpha    #container images
    #Environment können lokal oder auch auf dem entfernten Circleci gesetzt
    environment:
      # Date format to be used in naming "yyyymmddHHMM" (Shellscripting Code)
      VERSION_DATE : $(date +%Y%m%d%k%M)
      APK_PATH: '/outputs/apk/app-debug.apk'

    steps:
      - checkout

      - run:
          name: Ausgabe environment Variablen
          command: env
     
      # - run:
      #     name: Running tests   #Name of Circleci Step
      #     command: make test    #runs "make test" via Shell

      - run:
          name: Gradle build mit dem Zwecke Circleci Variablen (aus config.yml) an Gradle weiterreichen 
          command: ./gradlew

      - run:
          name: Gebe die eigenen Variablen aus
          command: |
            echo $VERSION_DATE
            echo $APK_PATH
            echo $APP_VERSION_NAME


dependencies:
    pre:
      # Update Android dependent SDK and tools
      # That settings need to be synced with Android Studio build settings
      - echo y | android update sdk --no-ui --all --filter tools,extra-android-m2repository,extra-android-support,android-25
      - echo y | android update sdk --no-ui --all --filter build-tools-25.0.2

test:
    override:
        - ./gradlew assembleDebug -PCIversionName=$APP_VERSION_NAME.$VERSION_DATE -PCIversionCode=$((APP_VERSION_CODE+1))
        - cp -r app/build/outputs $CIRCLE_ARTIFACTS

deployment:
  development:
    branch: master
    commands:
      # We want pass some information to shell script
      #   1. Build location 
      #   2. API token from environment variable (CircleCI dashboard)
      #   3. Hockey App APP_ID
      - ./scripts/deploy_hockeyapp.sh $CIRCLE_ARTIFACTS$APK_PATH $AWESOME_TOKEN $HOCKEYAPP_APP_ID

#$HOCKEYAPP_APP_ID

